print("home team half time score")
print("=========================")
input("enter home team half time score:  ")
input("enter away team half time score:  ")
print()
input("enter home team full time score:  ")
input("enter away team full time score:  ")
print()
print("the total number of goals")